# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: "Park Minho | JBNU Computer Science Department"
  params:
    description: "Sharing stories about Game Programming, Mobile, and AI."
  menu:
    main:
      - name: Home
        url: '#about'
        weight: 1

# Uncomment the lines below to configure your website in a second language.
ko:
  languageCode: ko-kr
  contentDir: content/ko
  title: "박민호 | 전북대학교 컴퓨터공학과"
  params:
    description: "전북대학교 컴퓨터공학과 박민호입니다. 게임 개발, AI, 모바일 프로그래밍에 대한 포트폴리오와 기술 블로그입니다."
  menu:
    main:
      - name: Home
        url: '#about'
        weight: 1
  