# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: "Creator"
  params:
    description: "Folio site for creating photos with Hugo Blox"
  menu:
    main:
      - name: Home
        url: '#about'
        weight: 1

# Uncomment the lines below to configure your website in a second language.
ko:
  languageCode: ko-kr
  contentDir: content/ko
  title: "Creator"
  params:
    description: "Hugo Blox로 만드는 포토폴리오 사이트"
  menu:
    main:
      - name: Home
        url: '#about'
        weight: 1
  