# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blog 
    url: blog/
    weight: 20
  - name: Topics
    url: tags/
    weight: 30
  - name: Uses
    url: uses/
    weight: 40
  - name: Resume
    url: uploads/resume.pdf
    weight: 50

  - name: 모든 게시물
    parent: Blog 
    url: 'blog/'
    weight: 1
  - name: 주제별 보기
    parent: Blog
    url: 'tags/'
    weight: 2